# Site
repository: parsa-j42
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Parsa Jafari
title: Student
email: parsajfri4@gmail.com
#website: www.github.com/parsa-j42

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  parsa-j42
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: parsa-j42
# xing_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
additional_links:
- title: CV
  icon: fas fa-file
  url: https://github.com/parsa-j42/parsa-j42.github.io/raw/main/CV.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url:

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: 
# gtag: 
# google_analytics: 

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Parsa and I'm currently a high school student. I like programming and I have experience in Python, JavaScript, TypeScript, Django, React, NestJS, HTML, CSS and SQL. I also have interest in linux and FOSS.

  I am most skilled in: <mark>Python</mark>

content:
  - title: Current Project(s) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        #title: 
        #link: 
        # link_text: Project Website
        #additional_links:
        #  - title: 
        #    icon: fab fa-github
        #    url: 
          # - title:  
          #   icon: fab fa-github
          #   url:
        #quote: >
          #
        description: | # this will include new lines to allow paragraphs
          Currently, I am trying to build up some experience in <mark>React</mark> and <mark>NestJS</mark>. According to Stack Overflow 2021 survey, the most commonly used web framework in 2021 was React, which is a good reason to gain skills in React. I also figured out that NestJS is one of my best choices to use for backend.
 # - title: Experience 
 #   layout: list # Type of content section (list/text)
 #   content:
 #    - layout: left
 #      title: 
 #      link: 
        # link_text: 
 #      sub_title: 
 #      caption: 
 #      quote: >
 #        
 #       description: | # this will include new lines to allow paragraphs
 #           

 # - title: Education
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: left
 #       title: 
 #       caption: 
 #       sub_title: 
 #       quote: >
 #
 #       description: |
 #    

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering and computers some of my other interests and hobbies are:
      - Playing Piano
      - Soccer
      - Gaming


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
