# Site
repository: parsa-j42
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Parsa Jafari
title: Software Developer
email: parsajfri42@gmail.com
website: https://www.linkedin.com/in/parsa-j42/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: parsa-j42
linkedin_username: parsa-j42

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-file
  url: # You can add your resume URL here

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  I am a Software Developer pursuing a Diploma in Software Development at Southern Alberta Institute of Technology (SAIT) with a GPA of 3.75/4.00. I have extensive experience in full-stack development using modern technologies and frameworks.

  I am proficient in: <mark>TypeScript</mark>, <mark>JavaScript</mark>, <mark>Python</mark>, <mark>React</mark>, <mark>Node.js</mark>, <mark>NestJS</mark>, <mark>React Native</mark>, <mark>HTML</mark>, <mark>CSS</mark>, <mark>ES6</mark>, <mark>Java</mark>, <mark>SQL</mark>, <mark>Git</mark>, and <mark>GNU/Linux</mark>.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Frontend Developer - Educational AI Platform
        caption: May 2024 - Oct 2024
        description: |
          - Led complete development of CaseCraft using React, TypeScript, Vite, and Mantine UI
          - Built key features including context-based customization, AI integration for scenario generation
          - Contributed to Ally's frontend development with AI-powered personalized learning
          - Implemented core UI architecture and user authentication using AWS Cognito and AWS Amplify

      - layout: left
        title: Mobile App Developer - Sidewalk Navigation Project
        sub_title: University of Calgary
        caption: Jul 2022 - Aug 2022
        description: |
          - Developed full-stack native mobile application for iOS and Android platforms
          - Implemented API endpoints using Node.js and Firebase
          - Built responsive UI/UX using React Native with Google Maps integration
          - Collaborated using Git and GitHub for version control

      - layout: left
        title: Full-Stack Software Developer
        sub_title: Meyar Keyfiat Co.
        caption: Jul 2021 - Jan 2022
        description: |
          - Developed web application using Django and Python for real-time data management
          - Designed scalable database schema using SQLite
          - Created user-friendly interface for efficient data rendering
          - Maintained regular client communication for project alignment

  - title: Education
    layout: list
    content:
      - layout: left
        title: Southern Alberta Institute of Technology (SAIT)
        caption: Expected Graduation April 2025
        sub_title: Diploma in Software Development
        quote: >
          GPA: 3.75 / 4.00

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: CompTIA Network+
        caption: March 2019
        sub_title: Issued by SEMATEC

      - layout: left
        title: Web Design
        caption: March 2019
        sub_title: Issued by SEMATEC
        description: |
          HTML, CSS, Dreamweaver, Bootstrap, Javascript, JQuery

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
